name: Build and Package application

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CONTAINER_NAME: rewardhub


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: 34.125.34.237
            username: csuftitan
            key: ${{ secrets.KEY }}
            port: 22
            script:  |
               sudo docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GIT_TOKEN }} 
               sudo docker compose -f /home/csuftitan/application/docker-compose.yml pull 
               sudo docker compose -f /home/csuftitan/application/docker-compose.yml up -d
